user www-data;                                # System user that will execute nginx
worker_processes auto;                        # Nº of worker processes. Auto = 1 per CPU
pid /run/nginx.pid;                           # Where the process PID will be stored
error_log /var/log/nginx/error.log;           # Error log location
include /etc/nginx/modules-enabled/*.conf;    # Including modules for nginx

events {
        worker_connections 768;               # Max of conections per worker
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;                           # Optimization using kernel
        tcp_nopush on;                         # TCP optimization, as it uses bigger packets
        types_hash_max_size 2048;              # Size of hash table for MIME files

        include /etc/nginx/mime.types;         # List of MIME files
        default_type application/octet-stream; # Default file tipe

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Protocls enabled (Should only be TLSv1.3)
        ssl_prefer_server_ciphers on;                # Makes the server decide the ciphers

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;       # Logs location

        ##
        # Gzip Settings
        ##

        gzip on;     # gzip compression

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;        # Aditional conf files
        include /etc/nginx/sites-enabled/*;      # Sites enabled for the server
}


