name: inception

services:
  proxy:
    image: inception/nginx
    container_name: nginx_container
    pull_policy: build
    build:
      context: ./requirements/nginx
    ports:
      - 8433:433
      - 8080:80    # DEDBUG, remove later

  db:
    image: inception/mariadb
    container_name: mariadb_container
    pull_policy: build
    build:
      context: ./requirements/mariadb
    secrets:
      - db_user
      - db_pass
      - db_name
    volumes:
      - db_data:/var/lib/mysql


secrets:
  db_user:
    file: ../secrets/db_user
  db_pass:
    file: ../secrets/db_pass
  db_name:
    file: ../secrets/db_name

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DIR}
